spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/database?serverTimezone=UTC
    username: root
    password: QazpLm321#@
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always